### ISSUE TITLE
Nothing at this URL

### ISSUE THREAD

**Issue by zpget** [Netflix/flamescope#169]
init info:

* Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 302-914-847

visit  http://127.0.0.1:5000/, get
{
"error": "Sorry, Nothing at this URL."
}

**Comment by duarten** [comment]
You probably need to build the client:

```
$ npm install
$ npm run webpack
```

**Comment by zpget** [comment]
Error 500
Unknown mime type.
![image](https://user-images.githubusercontent.com/10464357/208857277-7159e57c-ef57-4c32-a268-2066eed9b7ed.png)


> You probably need to build the client:
> 
> ```
> $ npm install
> $ npm run webpack
> ```

**Comment by zpget** [comment]
> Error 500 Unknown mime type. ![image](https://user-images.githubusercontent.com/10464357/208857277-7159e57c-ef57-4c32-a268-2066eed9b7ed.png)
> 
> > You probably need to build the client:
> > ```
> > $ npm install
> > $ npm run webpack
> > ```

GET /heatmap/?filename=perf.test01&type=perf&rows=50 HTTP/1.1" 500
node version v18.12.1

**Comment by Desislav-Petrov** [comment]
Had the same issue (nothing at url) - the npm install commands fixed it, doing a PR to update the readme. Thanks for the suggested fix @zpget

**Comment by akochepasov** [comment]
I had the same issue. Rinning `python run.py` resulted in the "Sorry, Nothing at this URL." error. Installing 
```
$ npm install
$ npm run webpack
```
fixed it.

**Comment by JSoet** [comment]
Caused by:  https://github.com/Netflix/flamescope/issues/150

**Comment by SinOverCos** [comment]
This doesn't quite fix it for me:

```
flamescope (master @ be26595) ~> npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 908 packages from 462 contributors in 14.683s

105 packages are looking for funding
  run `npm fund` for details


flamescope (master @ be26595) ~> npm run webpack

> flamescope@0.3.0 webpack /tmp/dockerv/flamescope
> NODE_ENV=production webpack --mode production

[webpack-cli] SyntaxError: Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/: Invalid escape
    at pathToArgumentName (/tmp/dockerv/flamescope/node_modules/webpack/lib/cli.js:66:4)
    at addFlag (/tmp/dockerv/flamescope/node_modules/webpack/lib/cli.js:170:16)
    at traverse (/tmp/dockerv/flamescope/node_modules/webpack/lib/cli.js:243:21)
    at traverse (/tmp/dockerv/flamescope/node_modules/webpack/lib/cli.js:299:23)
    at traverse (/tmp/dockerv/flamescope/node_modules/webpack/lib/cli.js:248:24)
    at Object.getArguments (/tmp/dockerv/flamescope/node_modules/webpack/lib/cli.js:308:2)
    at WebpackCLI.getBuiltInOptions (/tmp/dockerv/flamescope/node_modules/webpack-cli/lib/webpack-cli.js:905:41)
    at makeCommand (/tmp/dockerv/flamescope/node_modules/webpack-cli/lib/webpack-cli.js:1066:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! flamescope@0.3.0 webpack: `NODE_ENV=production webpack --mode production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the flamescope@0.3.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tanwang/.npm/_logs/2023-10-18T15_26_44_965Z-debug.log
```

**Comment by JSoet** [comment]
@SinOverCos 
That looks like a separate error that the project isn't building properly for you (although strangely it looks like it's an error in the webpack code), I'd open a separate issue about that

**Comment by GoodDayGeorge** [comment]
This also doesn't quite fix it for me: 

Ubuntu 20.04.6 LTS     nodejs v10.19.0

```
$ npm run webpack
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 908 packages from 462 contributors in 9.671s

109 packages are looking for funding
  run `npm fund` for details

$ npm run webpack

> flamescope@0.3.0 webpack /home/zhuxing/flamescope
> NODE_ENV=production webpack --mode production

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
assets by status 592 KiB [cached] 2 assets
orphan modules 462 KiB [orphan] 339 modules
runtime modules 1.25 KiB 6 modules
modules by path ./node_modules/ 1.14 MiB 400 modules
modules by path ./src/ 309 KiB
  ./src/index.jsx + 145 modules 308 KiB [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./src/components/FlameGraph/flamegraph.less 497 bytes [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./src/components/Heatmap/heatmap.less 1020 bytes [built] [code generated]
./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./semantic/semantic.less 39 bytes [built] [code generated] [1 error]

ERROR in ./semantic/semantic.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./semantic/semantic.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):


@import url(https://fonts.googleapis.com/css?family=Roboto);
^
Resource 'https://fonts.googleapis.com/css?family=Roboto' gave this Error:
  Error: socket hang up

      Error in  /home/zhuxing/flamescope/node_modules/semantic-ui-less/themes/material/collections/menu.overrides (line 1, column 0)
Error:

@import url(https://fonts.googleapis.com/css?family=Roboto);
^
Resource 'https://fonts.googleapis.com/css?family=Roboto' gave this Error:
  Error: socket hang up

      Error in  /home/zhuxing/flamescope/node_modules/semantic-ui-less/themes/material/collections/menu.overrides (line 1, column 0)
    at Object.lessLoader ( /home/zhuxing/flamescope/node_modules/less-loader/dist/index.js:54:14)
 @ ./semantic/semantic.less 8:6-171 22:17-24 26:0-141 26:0-141 27:22-29 27:33-47 27:50-64
 @ ./src/App.jsx 23:0-35
 @ ./src/index.jsx 25:0-24 34:7-10

webpack 5.58.2 compiled with 1 error in 34687 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flamescope@0.3.0 webpack: `NODE_ENV=production webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flamescope@0.3.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!      /home/zhuxing/.npm/_logs/2023-10-26T14_06_57_007Z-debug.log
```

**Comment by GoodDayGeorge** [comment]
okay, I copy the `app/public` from `https://github.com/Netflix/flamescope/tree/v0.2.0` to the `master` branch, it works. Consider it as a temporary workaround.

**Comment by VorpalBlade** [comment]
The webpack command doesn't work, I get yet another error:

```console
$ npm run webpack

> flamescope@0.3.0 webpack
> NODE_ENV=production webpack --mode production

node:internal/crypto/hash:103
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:103:19)
    at Object.createHash (node:crypto:137:10)
    at BulkUpdateDecorator.hashFactory (/home/arvid/src/profiling/flamescope/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/home/arvid/src/profiling/flamescope/node_modules/webpack/lib/util/createHash.js:80:21)
    at /home/arvid/src/profiling/flamescope/node_modules/webpack/lib/DefinePlugin.js:595:38
    at Hook.eval [as call] (eval at create (/home/arvid/src/profiling/flamescope/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (/home/arvid/src/profiling/flamescope/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/arvid/src/profiling/flamescope/node_modules/webpack/lib/Compiler.js:1053:26)
    at /home/arvid/src/profiling/flamescope/node_modules/webpack/lib/Compiler.js:1097:29
    at Hook.eval [as callAsync] (eval at create (/home/arvid/src/profiling/flamescope/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v24.5.0
```

I'm not a js dev, so I have no idea what to do here.

**Comment by computerquip-work** [comment]
Hi! So I was able to get this to work. The dependencies in particular are just very out of date. I had to delete package-lock.json (and make sure node_modules is also deleted), then regenerate it with an `npm install`. Then `npm run webpack` should work and `uv run run.py` or whatever tool you're using for venv should work.
