### ISSUE TITLE
master currently not running

### ISSUE THREAD

**Issue by SergejIsbrecht** [Netflix/flamescope#65]
Hi there,

currently when fetching the origin/master HEAD and trying to use python run.py on ubuntu it will not run due to some import issues:

sergej@L530:~/GitHub/flamescope$ python run.py 
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from app import APP
  File "/home/sergej/GitHub/flamescope/app/__init__.py", line 34, in <module>
    from app.views.flame_graph import MOD_FLAME_GRAPH
  File "/home/sergej/GitHub/flamescope/app/views/flame_graph.py", line 21, in <module>
    from app.controllers.flame_graph import generate_flame_graph
  File "/home/sergej/GitHub/flamescope/app/controllers/flame_graph.py", line 21, in <module>
    from app.common.fileutil import get_profile_type
  File "/home/sergej/GitHub/flamescope/app/common/fileutil.py", line 25, in <module>
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError

It looks like this issue is caused by recent restructuring. When I revert to some later commit everything workds just fine.

**Comment by SergejIsbrecht** [comment]
Issue has been resolved using pip3 and python3 under ubuntu instead od python (which is 2.7).

pip3 install -r ...
python3 run.py
