### ISSUE TITLE
Various issues making it work

### ISSUE THREAD

**Issue by vdmz** [Netflix/flamescope#73]
Hi

To get this nice tool working I had to make a few tweaks (after setting up a virtualenv)
```
% python -m pip list
Package       Version
------------- -------
cachetools    3.0.0  
click         6.7    
Flask         0.12.2 
itsdangerous  0.24   
Jinja2        2.10   
MarkupSafe    1.0    
pip           19.0.3 
pkg-resources 0.0.0  
protobuf      3.6.1  
python-magic  0.4.15 
setuptools    40.8.0 
simplejson    3.16.0 
six           1.12.0 
Werkzeug      0.14.1 
wheel         0.33.1 
```
First issue -
```
ImportError: No module named cpuprofile.flame_graph
```
and similarly for trace_event.flame_graph. I was able to fix this with:
```
$ touch app/cpuprofile/__init__.py
$ touch app/trace_event/__init__.py
```

Second issue - the version of the 'json' module did not have the JSONDecodeError method.
```
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from app import APP
  File "/data/git/clones/flamescope/app/__init__.py", line 34, in <module>
    from app.views.flame_graph import MOD_FLAME_GRAPH
  File "/data//git/clones/flamescope/app/views/flame_graph.py", line 21, in <module>
    from app.controllers.flame_graph import generate_flame_graph
  File "/data/git/clones/flamescope/app/controllers/flame_graph.py", line 25, in <module>
    from app.trace_event.flame_graph import trace_event_generate_flame_graph
  File "/data/git/clones/flamescope/app/trace_event/flame_graph.py", line 26, in <module>
    from json.decoder import JSONDecodeError
ImportError: cannot import name JSONDecodeError

```
Perhaps you should specify the one you want in requirements.txt or just use simplejson as below.
For me the fix was
```
$ git diff
diff --git a/app/trace_event/flame_graph.py b/app/trace_event/flame_graph.py
index 6e8df08..8c56745 100644
--- a/app/trace_event/flame_graph.py
+++ b/app/trace_event/flame_graph.py
@@ -23,7 +23,7 @@
 import json
 import math
 from flask import abort
-from json.decoder import JSONDecodeError
+from simplejson.decoder import JSONDecodeError
 from app.common.fileutil import get_file
 from app.trace_event.common import get_time_range
 
diff --git a/app/trace_event/heatmap.py b/app/trace_event/heatmap.py
index 261eca3..c12e5f6 100644
--- a/app/trace_event/heatmap.py
+++ b/app/trace_event/heatmap.py
@@ -24,7 +24,7 @@ import collections
 import math
 import json
 from flask import abort
-from json.decoder import JSONDecodeError
+from simplejson.decoder import JSONDecodeError
 
 from app.common.fileutil import get_file
 from app.trace_event.common import get_time_range
```

**Comment by spiermar** [comment]
1 is fixed. 2, assuming you are using Python 2.

**Comment by spiermar** [comment]
https://github.com/Netflix/flamescope/commit/6039df6e50ca7146104919708dcf989356418861 should fix the second issue, although I expect you will find more issues using Python 2.

**Comment by vdmz** [comment]
Thank you for that, I was indeed using python2.

I redid the set up using python3
```
% virtualenv -p /usr/bin/python3 flamenv
% source flamenv/bin/activate.csh
[flamenv] % python -m pip install -r requirements.txt
[flamenv] % python run.py
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 100-034-253
```

so all done here I think.
